#####################################
###  TOMCAT SERVER CONFIGURATION ####
#####################################
server:
  servlet:
    context-path: /auth
#####################################
####  Data Source Configuration #####
#####################################
spring:
  datasource:
    url: ${AUTH_DATASOURCE_URL}
    username: ${AUTH_DATASOURCE_USERNAME}
    password: ${AUTH_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  #####################################
  #######  Flyway Configuration #######
  #####################################
  flyway:
    locations: ${AUTH_FLYWAY_SCRIPT_LOCATION}
    baseline-on-migrate: true
#####################################
#######  Logging Configuration ######
#####################################
logging:
  level:
    root: INFO
    web: INFO
    org.hibernate: INFO