CREATE TABLE AUTHORITY
(
  ID   BIGSERIAL NOT NULL,
  NAME VARCHAR(255),
  PRIMARY KEY (ID),
  CONSTRAINT AUTHORITY_NAME_FK UNIQUE (NAME)
);

CREATE TABLE USER_
(
  ID                  BIGSERIAL NOT NULL,
  ACCOUNT_EXPIRED     BOOLEAN,
  ACCOUNT_LOCKED      BOOLEAN,
  CREDENTIALS_EXPIRED BOOLEAN,
  ENABLED             BOOLEAN,
  PASSWORD            VARCHAR(255),
  USER_NAME           VARCHAR(255),
  PRIMARY KEY (ID),
  CONSTRAINT USER_USER_NAME_UK UNIQUE (USER_NAME)
);

CREATE TABLE USER_AUTHORITY
(
  USER_ID      INT8 NOT NULL,
  AUTHORITY_ID INT8 NOT NULL,
  PRIMARY KEY (USER_ID, AUTHORITY_ID),
  CONSTRAINT USERS_AUTHORITIES_AUTHORITY_FK FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY,
  CONSTRAINT USERS_AUTHORITIES_USER_FK FOREIGN KEY (USER_ID) REFERENCES USER_
);