INSERT INTO AUTHORITY(NAME) VALUES ('PRODUCT_READ');
INSERT INTO AUTHORITY(NAME) VALUES ('PRODUCT_CREATE');
INSERT INTO AUTHORITY(NAME) VALUES ('PRODUCT_UPDATE');
INSERT INTO AUTHORITY(NAME) VALUES ('PRODUCT_DELETE');

INSERT INTO AUTHORITY(NAME) VALUES ('CUSTOMER_READ');
INSERT INTO AUTHORITY(NAME) VALUES ('CUSTOMER_CREATE');
INSERT INTO AUTHORITY(NAME) VALUES ('CUSTOMER_UPDATE');
INSERT INTO AUTHORITY(NAME) VALUES ('CUSTOMER_DELETE');

INSERT INTO AUTHORITY(NAME) VALUES ('OUTCOME_READ');
INSERT INTO AUTHORITY(NAME) VALUES ('OUTCOME_CREATE');
INSERT INTO AUTHORITY(NAME) VALUES ('OUTCOME_UPDATE');
INSERT INTO AUTHORITY(NAME) VALUES ('OUTCOME_DELETE');